server:
  port: 8080
spring:
  application:
    name: demodeploy
  datasource:
    url: jdbc:postgresql://localhost:5432/demodeploy
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true