package com.nocode.platform.generator.engine;

import com.nocode.platform.generator.engine.poet.ControllerGenerator;
import com.nocode.platform.generator.engine.poet.EntityGenerator;
import com.nocode.platform.generator.engine.poet.RepositoryGenerator;
import com.nocode.platform.generator.spec.Spec;
import com.nocode.platform.generator.template.TemplateRenderer;

import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Map;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

/**
 * Главный генератор проекта — собирает все части в ZIP-архив.
 *
 * <p>Координирует работу всех генераторов: сущности (JavaPoet),
 * репозитории, контроллеры, Liquibase changelog, модуль безопасности,
 * ActionFlow-сервисы и React-фронтенд (FreeMarker).</p>
 */
public class ProjectGenerator {

    private final TemplateRenderer renderer = new TemplateRenderer();
    private final EntityGenerator entityGenerator = new EntityGenerator();
    private final RepositoryGenerator repoGenerator = new RepositoryGenerator();
    private final ControllerGenerator controllerGenerator = new ControllerGenerator();
    private final LiquibaseGenerator liquibaseGenerator = new LiquibaseGenerator();
    private final FrontendGenerator frontendGenerator = new FrontendGenerator();
    private final com.nocode.platform.generator.engine.poet.ServiceGenerator actionFlowServiceGenerator = new com.nocode.platform.generator.engine.poet.ServiceGenerator();
    private final com.nocode.platform.generator.engine.poet.ActionFlowControllerGenerator actionFlowControllerGenerator = new com.nocode.platform.generator.engine.poet.ActionFlowControllerGenerator();

    /**
     * Генерация полного проекта в виде ZIP-архива.
     *
     * @param spec спецификация проекта
     * @return массив байтов ZIP-архива
     */
    public byte[] generate(Spec spec) {
        String artifactId = spec.project().artifactId();
        String groupId = spec.project().groupId();
        String version = (spec.project().version() == null || spec.project().version().isBlank())
                ? "0.1.0-SNAPSHOT"
                : spec.project().version();
        String basePackage = spec.project().basePackage();
        String appName = spec.project().name();

        String root = artifactId + "/";

        Map<String, Object> model = new HashMap<>();
        model.put("groupId", groupId);
        model.put("artifactId", artifactId);
        model.put("version", version);
        model.put("basePackage", basePackage);
        model.put("appName", appName);
        model.put("authEnabled", spec.project().authEnabled());

        String pomXml = renderer.render("pom.ftl", model);
        String appJava = renderer.render("Application.java.ftl", model);
        String applicationYml = renderer.render("application.yml.ftl", model);
        String changelogYaml = liquibaseGenerator.generateChangelog(spec.entities(), spec.project().authEnabled());

        // com.a.b -> com/a/b
        String pkgPath = basePackage.replace('.', '/');

        try (ByteArrayOutputStream baos = new ByteArrayOutputStream();
             ZipOutputStream zos = new ZipOutputStream(baos, StandardCharsets.UTF_8)) {

            putText(zos, root + "backend/pom.xml", pomXml);
            putText(zos, root + "backend/README.md", "# " + appName + "\nGenerated by No-code platform\n");
            putText(zos, root + "spec.yaml", "specVersion: " + spec.specVersion() + "\n");

            putText(zos, root + "backend/src/main/resources/application.yml", applicationYml);
            putText(zos, root + "backend/src/main/resources/db/changelog/db.changelog-master.yaml", changelogYaml);
            
            putText(zos, root + "backend/src/main/java/" + pkgPath + "/Application.java", appJava);

            if (spec.project().authEnabled()) {
                SecurityGenerator secGen = new SecurityGenerator();
                secGen.generate(zos, root + "backend/", pkgPath, basePackage);
            }

            if (spec.entities() != null) {
                for (Spec.Entity entity : spec.entities()) {
                    String entityCode = entityGenerator.generate(entity, basePackage);
                    String repoCode = repoGenerator.generate(entity, basePackage);
                    String controllerCode = controllerGenerator.generate(entity, basePackage, spec.project().authEnabled());

                    String entityPath = root + "backend/src/main/java/" + pkgPath + "/domain/" + entity.name() + ".java";
                    String repoPath = root + "backend/src/main/java/" + pkgPath + "/repository/" + entity.name() + "Repository.java";
                    String controllerPath = root + "backend/src/main/java/" + pkgPath + "/controller/" + entity.name() + "Controller.java";

                    putText(zos, entityPath, entityCode);
                    putText(zos, repoPath, repoCode);
                    putText(zos, controllerPath, controllerCode);
                }
            }

            if (spec.actionFlows() != null && !spec.actionFlows().isEmpty()) {
                String serviceCode = actionFlowServiceGenerator.generate(spec, basePackage);
                String servicePath = root + "backend/src/main/java/" + pkgPath + "/service/ActionFlowService.java";
                putText(zos, servicePath, serviceCode);

                String controllerCode = actionFlowControllerGenerator.generate(spec, basePackage);
                String controllerPath = root + "backend/src/main/java/" + pkgPath + "/controller/ActionFlowController.java";
                putText(zos, controllerPath, controllerCode);
            }

            if (spec.project().generateFrontend()) {
                frontendGenerator.generate(zos, root + "frontend/", spec);
            }

            zos.finish();
            return baos.toByteArray();
        } catch (Exception e) {
            throw new IllegalStateException("ZIP build failed: " + e.getMessage(), e);
        }
    }

    private void putText(ZipOutputStream zos, String path, String content) throws Exception {
        ZipEntry entry = new ZipEntry(path);
        zos.putNextEntry(entry);
        zos.write(content.getBytes(StandardCharsets.UTF_8));
        zos.closeEntry();
    }
}