server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/nocode_platform
    username: nocode
    password: nocode
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  # чтобы НЕ было двойного запуска (мы запускаем Liquibase через LiquibaseConfig)
  liquibase:
    enabled: false

logging:
  level:
    com.zaxxer.hikari: INFO
    liquibase: INFO