server:
  port: 8082

spring:
  application:
    name: platform-web
  datasource:
    url: jdbc:postgresql://127.0.0.1:5434/nocode_platform
    username: nocode
    password: nocode_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  # чтобы НЕ было двойного запуска (мы запускаем Liquibase через LiquibaseConfig)
  liquibase:
    enabled: false

logging:
  level:
    com.zaxxer.hikari: INFO
    liquibase: INFO
    org.springframework.security: TRACE